### ISSUE TITLE
Deploy in Heroku

### ISSUE THREAD

**Issue by mrivh** [BC-MAY-21-ROR/kata-06-reloj-checador-k06-t04#36]
# REQUIREMENTS
Launch app in Heroku.

# Acceptance Criteria

- [x] Coordinate our Github repository.
- [x] Succesful launch of our app in Heroku.

**Comment by SampabloC** [comment]
Deploy completed on heroku and connected to repository on the next link:
[https://kata-06-reloj-checador-k06-t04.herokuapp.com/](url)
![imagen](https://user-images.githubusercontent.com/38772008/126412509-0ba46360-3f0e-4098-96f1-a399b6f6b0ad.png)
